// Generated by CoffeeScript 1.6.2
window.PaperSections = {};

window.PaperSections.$container = $('#wrapper');

window.PaperSections.i = 0;

window.PaperSections.next = 0;

window.PaperSections.next2 = 0;

window.PaperSections.scSpeed = 0;

window.PaperSections.prev = 0;

window.PaperSections.prev2 = 0;

window.PaperSections.scrollSpeed = 0;

window.PaperSections.scrollSpeed2 = 0;

window.PaperSections.timeOut = null;

window.PaperSections.anima = false;

window.PaperSections.animaListener = false;

window.PaperSections.slice = function(val, max) {
  if (val > 0 && val > max) {
    return Math.min(val, max);
  }
  if (val < 0 && val < max) {
    return Math.max(val, -max);
  }
  return val;
};

window.PaperSections.$container.scroll(function(e) {
  clearTimeout(window.PaperSections.timeOut);
  window.PaperSections.timeOut = setTimeout(function() {
    window.PaperSections.i = 0;
    window.PaperSections.$container.trigger('stopScroll');
    return window.PaperSections.prev = window.PaperSections.$container.scrollTop();
  }, 50);
  if (window.PaperSections.i % 4 === 0) {
    window.PaperSections.next = window.PaperSections.$container.scrollTop();
    window.PaperSections.scrollSpeed = window.PaperSections.slice(window.PaperSections.next - window.PaperSections.prev, 135);
    window.PaperSections.prev = window.PaperSections.next;
  }
  return window.PaperSections.i++;
});
